// <auto-generated />
using System;
using Fora;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fora.Migrations
{
    [DbContext(typeof(EdgarCompanyDataContext))]
    [Migration("20240928154420_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Property<long>("Cik")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Cik");

                    b.ToTable("EdgarCompanyDataList");

                    b.HasData(
                        new
                        {
                            Cik = 18926L
                        },
                        new
                        {
                            Cik = 892553L
                        },
                        new
                        {
                            Cik = 1510524L
                        },
                        new
                        {
                            Cik = 1858912L
                        },
                        new
                        {
                            Cik = 1828248L
                        },
                        new
                        {
                            Cik = 1819493L
                        },
                        new
                        {
                            Cik = 60086L
                        },
                        new
                        {
                            Cik = 1853630L
                        },
                        new
                        {
                            Cik = 1761312L
                        },
                        new
                        {
                            Cik = 1851182L
                        },
                        new
                        {
                            Cik = 1034665L
                        },
                        new
                        {
                            Cik = 927628L
                        },
                        new
                        {
                            Cik = 1125259L
                        },
                        new
                        {
                            Cik = 1547660L
                        },
                        new
                        {
                            Cik = 1393311L
                        },
                        new
                        {
                            Cik = 1757143L
                        },
                        new
                        {
                            Cik = 1958217L
                        },
                        new
                        {
                            Cik = 312070L
                        },
                        new
                        {
                            Cik = 310522L
                        },
                        new
                        {
                            Cik = 1861841L
                        },
                        new
                        {
                            Cik = 1037868L
                        },
                        new
                        {
                            Cik = 1696355L
                        },
                        new
                        {
                            Cik = 1166834L
                        },
                        new
                        {
                            Cik = 915912L
                        },
                        new
                        {
                            Cik = 1085277L
                        },
                        new
                        {
                            Cik = 831259L
                        },
                        new
                        {
                            Cik = 882291L
                        },
                        new
                        {
                            Cik = 1521036L
                        },
                        new
                        {
                            Cik = 1824502L
                        },
                        new
                        {
                            Cik = 1015647L
                        },
                        new
                        {
                            Cik = 884624L
                        },
                        new
                        {
                            Cik = 1501103L
                        },
                        new
                        {
                            Cik = 1397183L
                        },
                        new
                        {
                            Cik = 1552797L
                        },
                        new
                        {
                            Cik = 1894630L
                        },
                        new
                        {
                            Cik = 823277L
                        },
                        new
                        {
                            Cik = 21175L
                        },
                        new
                        {
                            Cik = 1439124L
                        },
                        new
                        {
                            Cik = 52827L
                        },
                        new
                        {
                            Cik = 1730773L
                        },
                        new
                        {
                            Cik = 1867287L
                        },
                        new
                        {
                            Cik = 1685428L
                        },
                        new
                        {
                            Cik = 1007587L
                        },
                        new
                        {
                            Cik = 92103L
                        },
                        new
                        {
                            Cik = 1641751L
                        },
                        new
                        {
                            Cik = 6845L
                        },
                        new
                        {
                            Cik = 1231457L
                        },
                        new
                        {
                            Cik = 947263L
                        },
                        new
                        {
                            Cik = 895421L
                        },
                        new
                        {
                            Cik = 1988979L
                        },
                        new
                        {
                            Cik = 1848898L
                        },
                        new
                        {
                            Cik = 844790L
                        },
                        new
                        {
                            Cik = 1541309L
                        },
                        new
                        {
                            Cik = 1858007L
                        },
                        new
                        {
                            Cik = 1729944L
                        },
                        new
                        {
                            Cik = 726958L
                        },
                        new
                        {
                            Cik = 1691221L
                        },
                        new
                        {
                            Cik = 730272L
                        },
                        new
                        {
                            Cik = 1308106L
                        },
                        new
                        {
                            Cik = 884144L
                        },
                        new
                        {
                            Cik = 1108134L
                        },
                        new
                        {
                            Cik = 1849058L
                        },
                        new
                        {
                            Cik = 1435617L
                        },
                        new
                        {
                            Cik = 1857518L
                        },
                        new
                        {
                            Cik = 64803L
                        },
                        new
                        {
                            Cik = 1912498L
                        },
                        new
                        {
                            Cik = 1447380L
                        },
                        new
                        {
                            Cik = 1232384L
                        },
                        new
                        {
                            Cik = 1141788L
                        },
                        new
                        {
                            Cik = 1549922L
                        },
                        new
                        {
                            Cik = 914475L
                        },
                        new
                        {
                            Cik = 1498382L
                        },
                        new
                        {
                            Cik = 1400897L
                        },
                        new
                        {
                            Cik = 314808L
                        },
                        new
                        {
                            Cik = 1323885L
                        },
                        new
                        {
                            Cik = 1526520L
                        },
                        new
                        {
                            Cik = 1550695L
                        },
                        new
                        {
                            Cik = 1634293L
                        },
                        new
                        {
                            Cik = 1756708L
                        },
                        new
                        {
                            Cik = 1540159L
                        },
                        new
                        {
                            Cik = 1076691L
                        },
                        new
                        {
                            Cik = 1980088L
                        },
                        new
                        {
                            Cik = 1532346L
                        },
                        new
                        {
                            Cik = 923796L
                        },
                        new
                        {
                            Cik = 1849635L
                        },
                        new
                        {
                            Cik = 1872292L
                        },
                        new
                        {
                            Cik = 1227857L
                        },
                        new
                        {
                            Cik = 1046311L
                        },
                        new
                        {
                            Cik = 1710350L
                        },
                        new
                        {
                            Cik = 1476150L
                        },
                        new
                        {
                            Cik = 1844642L
                        },
                        new
                        {
                            Cik = 1967078L
                        },
                        new
                        {
                            Cik = 14272L
                        },
                        new
                        {
                            Cik = 933267L
                        },
                        new
                        {
                            Cik = 1157557L
                        },
                        new
                        {
                            Cik = 1560293L
                        },
                        new
                        {
                            Cik = 217410L
                        },
                        new
                        {
                            Cik = 1798562L
                        },
                        new
                        {
                            Cik = 1038074L
                        },
                        new
                        {
                            Cik = 1843370L
                        });
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("EdgarCompanyDataCik")
                        .HasColumnType("bigint");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Val")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EdgarCompanyDataCik");

                    b.ToTable("InfoFactUsGaapIncomeLossUnitsUsd");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.HasOne("Fora.Model.EdgarCompanyData", null)
                        .WithMany("Usd")
                        .HasForeignKey("EdgarCompanyDataCik");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Navigation("Usd");
                });
#pragma warning restore 612, 618
        }
    }
}
