// <auto-generated />
using System;
using Fora;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fora.Migrations
{
    [DbContext(typeof(EdgarCompanyDataContext))]
    [Migration("20240926205351_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Property<int>("Cik")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("Cik");

                    b.ToTable("EdgarCompanyDataList");

                    b.HasData(
                        new
                        {
                            Cik = 18926,
                            id = 0
                        },
                        new
                        {
                            Cik = 892553,
                            id = 0
                        },
                        new
                        {
                            Cik = 1510524,
                            id = 0
                        },
                        new
                        {
                            Cik = 1858912,
                            id = 0
                        },
                        new
                        {
                            Cik = 1828248,
                            id = 0
                        },
                        new
                        {
                            Cik = 1819493,
                            id = 0
                        },
                        new
                        {
                            Cik = 60086,
                            id = 0
                        },
                        new
                        {
                            Cik = 1853630,
                            id = 0
                        },
                        new
                        {
                            Cik = 1761312,
                            id = 0
                        },
                        new
                        {
                            Cik = 1851182,
                            id = 0
                        },
                        new
                        {
                            Cik = 1034665,
                            id = 0
                        },
                        new
                        {
                            Cik = 927628,
                            id = 0
                        },
                        new
                        {
                            Cik = 1125259,
                            id = 0
                        },
                        new
                        {
                            Cik = 1547660,
                            id = 0
                        },
                        new
                        {
                            Cik = 1393311,
                            id = 0
                        },
                        new
                        {
                            Cik = 1757143,
                            id = 0
                        },
                        new
                        {
                            Cik = 1958217,
                            id = 0
                        },
                        new
                        {
                            Cik = 312070,
                            id = 0
                        },
                        new
                        {
                            Cik = 310522,
                            id = 0
                        },
                        new
                        {
                            Cik = 1861841,
                            id = 0
                        },
                        new
                        {
                            Cik = 1037868,
                            id = 0
                        },
                        new
                        {
                            Cik = 1696355,
                            id = 0
                        },
                        new
                        {
                            Cik = 1166834,
                            id = 0
                        },
                        new
                        {
                            Cik = 915912,
                            id = 0
                        },
                        new
                        {
                            Cik = 1085277,
                            id = 0
                        },
                        new
                        {
                            Cik = 831259,
                            id = 0
                        },
                        new
                        {
                            Cik = 882291,
                            id = 0
                        },
                        new
                        {
                            Cik = 1521036,
                            id = 0
                        },
                        new
                        {
                            Cik = 1824502,
                            id = 0
                        },
                        new
                        {
                            Cik = 1015647,
                            id = 0
                        },
                        new
                        {
                            Cik = 884624,
                            id = 0
                        },
                        new
                        {
                            Cik = 1501103,
                            id = 0
                        },
                        new
                        {
                            Cik = 1397183,
                            id = 0
                        },
                        new
                        {
                            Cik = 1552797,
                            id = 0
                        },
                        new
                        {
                            Cik = 1894630,
                            id = 0
                        },
                        new
                        {
                            Cik = 823277,
                            id = 0
                        },
                        new
                        {
                            Cik = 21175,
                            id = 0
                        },
                        new
                        {
                            Cik = 1439124,
                            id = 0
                        },
                        new
                        {
                            Cik = 52827,
                            id = 0
                        },
                        new
                        {
                            Cik = 1730773,
                            id = 0
                        },
                        new
                        {
                            Cik = 1867287,
                            id = 0
                        },
                        new
                        {
                            Cik = 1685428,
                            id = 0
                        },
                        new
                        {
                            Cik = 1007587,
                            id = 0
                        },
                        new
                        {
                            Cik = 92103,
                            id = 0
                        },
                        new
                        {
                            Cik = 1641751,
                            id = 0
                        },
                        new
                        {
                            Cik = 6845,
                            id = 0
                        },
                        new
                        {
                            Cik = 1231457,
                            id = 0
                        },
                        new
                        {
                            Cik = 947263,
                            id = 0
                        },
                        new
                        {
                            Cik = 895421,
                            id = 0
                        },
                        new
                        {
                            Cik = 1988979,
                            id = 0
                        },
                        new
                        {
                            Cik = 1848898,
                            id = 0
                        },
                        new
                        {
                            Cik = 844790,
                            id = 0
                        },
                        new
                        {
                            Cik = 1541309,
                            id = 0
                        },
                        new
                        {
                            Cik = 1858007,
                            id = 0
                        },
                        new
                        {
                            Cik = 1729944,
                            id = 0
                        },
                        new
                        {
                            Cik = 726958,
                            id = 0
                        },
                        new
                        {
                            Cik = 1691221,
                            id = 0
                        },
                        new
                        {
                            Cik = 730272,
                            id = 0
                        },
                        new
                        {
                            Cik = 1308106,
                            id = 0
                        },
                        new
                        {
                            Cik = 884144,
                            id = 0
                        },
                        new
                        {
                            Cik = 1108134,
                            id = 0
                        },
                        new
                        {
                            Cik = 1849058,
                            id = 0
                        },
                        new
                        {
                            Cik = 1435617,
                            id = 0
                        },
                        new
                        {
                            Cik = 1857518,
                            id = 0
                        },
                        new
                        {
                            Cik = 64803,
                            id = 0
                        },
                        new
                        {
                            Cik = 1912498,
                            id = 0
                        },
                        new
                        {
                            Cik = 1447380,
                            id = 0
                        },
                        new
                        {
                            Cik = 1232384,
                            id = 0
                        },
                        new
                        {
                            Cik = 1141788,
                            id = 0
                        },
                        new
                        {
                            Cik = 1549922,
                            id = 0
                        },
                        new
                        {
                            Cik = 914475,
                            id = 0
                        },
                        new
                        {
                            Cik = 1498382,
                            id = 0
                        },
                        new
                        {
                            Cik = 1400897,
                            id = 0
                        },
                        new
                        {
                            Cik = 314808,
                            id = 0
                        },
                        new
                        {
                            Cik = 1323885,
                            id = 0
                        },
                        new
                        {
                            Cik = 1526520,
                            id = 0
                        },
                        new
                        {
                            Cik = 1550695,
                            id = 0
                        },
                        new
                        {
                            Cik = 1634293,
                            id = 0
                        },
                        new
                        {
                            Cik = 1756708,
                            id = 0
                        },
                        new
                        {
                            Cik = 1540159,
                            id = 0
                        },
                        new
                        {
                            Cik = 1076691,
                            id = 0
                        },
                        new
                        {
                            Cik = 1980088,
                            id = 0
                        },
                        new
                        {
                            Cik = 1532346,
                            id = 0
                        },
                        new
                        {
                            Cik = 923796,
                            id = 0
                        },
                        new
                        {
                            Cik = 1849635,
                            id = 0
                        },
                        new
                        {
                            Cik = 1872292,
                            id = 0
                        },
                        new
                        {
                            Cik = 1227857,
                            id = 0
                        },
                        new
                        {
                            Cik = 1046311,
                            id = 0
                        },
                        new
                        {
                            Cik = 1710350,
                            id = 0
                        },
                        new
                        {
                            Cik = 1476150,
                            id = 0
                        },
                        new
                        {
                            Cik = 1844642,
                            id = 0
                        },
                        new
                        {
                            Cik = 1967078,
                            id = 0
                        },
                        new
                        {
                            Cik = 14272,
                            id = 0
                        },
                        new
                        {
                            Cik = 933267,
                            id = 0
                        },
                        new
                        {
                            Cik = 1157557,
                            id = 0
                        },
                        new
                        {
                            Cik = 1560293,
                            id = 0
                        },
                        new
                        {
                            Cik = 217410,
                            id = 0
                        },
                        new
                        {
                            Cik = 1798562,
                            id = 0
                        },
                        new
                        {
                            Cik = 1038074,
                            id = 0
                        },
                        new
                        {
                            Cik = 1843370,
                            id = 0
                        });
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("EdgarCompanyDataCik")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Val")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("EdgarCompanyDataCik");

                    b.ToTable("InfoFactUsGaapIncomeLossUnitsUsd");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.HasOne("Fora.Model.EdgarCompanyData", null)
                        .WithMany("Usd")
                        .HasForeignKey("EdgarCompanyDataCik");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Navigation("Usd");
                });
#pragma warning restore 612, 618
        }
    }
}
