// <auto-generated />
using System;
using Fora;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fora.Migrations
{
    [DbContext(typeof(EdgarCompanyDataContext))]
    partial class EdgarCompanyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Property<int>("Cik")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Cik");

                    b.ToTable("EdgarCompanyDataList");

                    b.HasData(
                        new
                        {
                            Cik = 18926
                        },
                        new
                        {
                            Cik = 892553
                        },
                        new
                        {
                            Cik = 1510524
                        },
                        new
                        {
                            Cik = 1858912
                        },
                        new
                        {
                            Cik = 1828248
                        },
                        new
                        {
                            Cik = 1819493
                        },
                        new
                        {
                            Cik = 60086
                        },
                        new
                        {
                            Cik = 1853630
                        },
                        new
                        {
                            Cik = 1761312
                        },
                        new
                        {
                            Cik = 1851182
                        },
                        new
                        {
                            Cik = 1034665
                        },
                        new
                        {
                            Cik = 927628
                        },
                        new
                        {
                            Cik = 1125259
                        },
                        new
                        {
                            Cik = 1547660
                        },
                        new
                        {
                            Cik = 1393311
                        },
                        new
                        {
                            Cik = 1757143
                        },
                        new
                        {
                            Cik = 1958217
                        },
                        new
                        {
                            Cik = 312070
                        },
                        new
                        {
                            Cik = 310522
                        },
                        new
                        {
                            Cik = 1861841
                        },
                        new
                        {
                            Cik = 1037868
                        },
                        new
                        {
                            Cik = 1696355
                        },
                        new
                        {
                            Cik = 1166834
                        },
                        new
                        {
                            Cik = 915912
                        },
                        new
                        {
                            Cik = 1085277
                        },
                        new
                        {
                            Cik = 831259
                        },
                        new
                        {
                            Cik = 882291
                        },
                        new
                        {
                            Cik = 1521036
                        },
                        new
                        {
                            Cik = 1824502
                        },
                        new
                        {
                            Cik = 1015647
                        },
                        new
                        {
                            Cik = 884624
                        },
                        new
                        {
                            Cik = 1501103
                        },
                        new
                        {
                            Cik = 1397183
                        },
                        new
                        {
                            Cik = 1552797
                        },
                        new
                        {
                            Cik = 1894630
                        },
                        new
                        {
                            Cik = 823277
                        },
                        new
                        {
                            Cik = 21175
                        },
                        new
                        {
                            Cik = 1439124
                        },
                        new
                        {
                            Cik = 52827
                        },
                        new
                        {
                            Cik = 1730773
                        },
                        new
                        {
                            Cik = 1867287
                        },
                        new
                        {
                            Cik = 1685428
                        },
                        new
                        {
                            Cik = 1007587
                        },
                        new
                        {
                            Cik = 92103
                        },
                        new
                        {
                            Cik = 1641751
                        },
                        new
                        {
                            Cik = 6845
                        },
                        new
                        {
                            Cik = 1231457
                        },
                        new
                        {
                            Cik = 947263
                        },
                        new
                        {
                            Cik = 895421
                        },
                        new
                        {
                            Cik = 1988979
                        },
                        new
                        {
                            Cik = 1848898
                        },
                        new
                        {
                            Cik = 844790
                        },
                        new
                        {
                            Cik = 1541309
                        },
                        new
                        {
                            Cik = 1858007
                        },
                        new
                        {
                            Cik = 1729944
                        },
                        new
                        {
                            Cik = 726958
                        },
                        new
                        {
                            Cik = 1691221
                        },
                        new
                        {
                            Cik = 730272
                        },
                        new
                        {
                            Cik = 1308106
                        },
                        new
                        {
                            Cik = 884144
                        },
                        new
                        {
                            Cik = 1108134
                        },
                        new
                        {
                            Cik = 1849058
                        },
                        new
                        {
                            Cik = 1435617
                        },
                        new
                        {
                            Cik = 1857518
                        },
                        new
                        {
                            Cik = 64803
                        },
                        new
                        {
                            Cik = 1912498
                        },
                        new
                        {
                            Cik = 1447380
                        },
                        new
                        {
                            Cik = 1232384
                        },
                        new
                        {
                            Cik = 1141788
                        },
                        new
                        {
                            Cik = 1549922
                        },
                        new
                        {
                            Cik = 914475
                        },
                        new
                        {
                            Cik = 1498382
                        },
                        new
                        {
                            Cik = 1400897
                        },
                        new
                        {
                            Cik = 314808
                        },
                        new
                        {
                            Cik = 1323885
                        },
                        new
                        {
                            Cik = 1526520
                        },
                        new
                        {
                            Cik = 1550695
                        },
                        new
                        {
                            Cik = 1634293
                        },
                        new
                        {
                            Cik = 1756708
                        },
                        new
                        {
                            Cik = 1540159
                        },
                        new
                        {
                            Cik = 1076691
                        },
                        new
                        {
                            Cik = 1980088
                        },
                        new
                        {
                            Cik = 1532346
                        },
                        new
                        {
                            Cik = 923796
                        },
                        new
                        {
                            Cik = 1849635
                        },
                        new
                        {
                            Cik = 1872292
                        },
                        new
                        {
                            Cik = 1227857
                        },
                        new
                        {
                            Cik = 1046311
                        },
                        new
                        {
                            Cik = 1710350
                        },
                        new
                        {
                            Cik = 1476150
                        },
                        new
                        {
                            Cik = 1844642
                        },
                        new
                        {
                            Cik = 1967078
                        },
                        new
                        {
                            Cik = 14272
                        },
                        new
                        {
                            Cik = 933267
                        },
                        new
                        {
                            Cik = 1157557
                        },
                        new
                        {
                            Cik = 1560293
                        },
                        new
                        {
                            Cik = 217410
                        },
                        new
                        {
                            Cik = 1798562
                        },
                        new
                        {
                            Cik = 1038074
                        },
                        new
                        {
                            Cik = 1843370
                        });
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("EdgarCompanyDataCik")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Val")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("EdgarCompanyDataCik");

                    b.ToTable("InfoFactUsGaapIncomeLossUnitsUsd");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.HasOne("Fora.Model.EdgarCompanyData", null)
                        .WithMany("Usd")
                        .HasForeignKey("EdgarCompanyDataCik");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Navigation("Usd");
                });
#pragma warning restore 612, 618
        }
    }
}
