// <auto-generated />
using System;
using Fora;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fora.Migrations
{
    [DbContext(typeof(EdgarCompanyDataContext))]
    partial class EdgarCompanyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Property<long>("Cik")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("specialFundableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("standardFundableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Cik");

                    b.ToTable("EdgarCompanyDataList");

                    b.HasData(
                        new
                        {
                            Cik = 18926L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 892553L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1510524L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1858912L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1828248L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1819493L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 60086L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1853630L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1761312L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1851182L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1034665L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 927628L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1125259L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1547660L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1393311L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1757143L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1958217L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 312070L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 310522L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1861841L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1037868L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1696355L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1166834L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 915912L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1085277L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 831259L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 882291L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1521036L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1824502L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1015647L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 884624L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1501103L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1397183L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1552797L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1894630L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 823277L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 21175L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1439124L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 52827L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1730773L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1867287L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1685428L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1007587L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 92103L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1641751L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 6845L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1231457L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 947263L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 895421L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1988979L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1848898L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 844790L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1541309L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1858007L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1729944L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 726958L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1691221L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 730272L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1308106L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 884144L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1108134L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1849058L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1435617L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1857518L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 64803L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1912498L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1447380L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1232384L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1141788L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1549922L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 914475L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1498382L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1400897L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 314808L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1323885L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1526520L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1550695L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1634293L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1756708L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1540159L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1076691L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1980088L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1532346L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 923796L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1849635L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1872292L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1227857L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1046311L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1710350L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1476150L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1844642L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1967078L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 14272L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 933267L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1157557L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1560293L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 217410L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1798562L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1038074L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        },
                        new
                        {
                            Cik = 1843370L,
                            specialFundableAmount = 0m,
                            standardFundableAmount = 0m
                        });
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("EdgarCompanyDataCik")
                        .HasColumnType("bigint");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Val")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EdgarCompanyDataCik");

                    b.ToTable("InfoFactUsGaapIncomeLossUnitsUsd");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData+InfoFactUsGaapIncomeLossUnitsUsd", b =>
                {
                    b.HasOne("Fora.Model.EdgarCompanyData", null)
                        .WithMany("Usd")
                        .HasForeignKey("EdgarCompanyDataCik");
                });

            modelBuilder.Entity("Fora.Model.EdgarCompanyData", b =>
                {
                    b.Navigation("Usd");
                });
#pragma warning restore 612, 618
        }
    }
}
